// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVeY1QXOIVheLDvStxeEgfyQ96NwLLJN8',
    appId: '1:270100716047:web:6764904dcc46e93339217a',
    messagingSenderId: '270100716047',
    projectId: 'applygit',
    authDomain: 'applygit.firebaseapp.com',
    storageBucket: 'applygit.appspot.com',
    measurementId: 'G-PY9KNS6PGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXD9gN_nmR1vWRW5hMgbSgQmpeY2TTbck',
    appId: '1:270100716047:android:38280dddc467a12b39217a',
    messagingSenderId: '270100716047',
    projectId: 'applygit',
    storageBucket: 'applygit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsyodqaYO_wDfhyBxYDbB57rvyNcwBzKA',
    appId: '1:270100716047:ios:c0f8fc3db2d92e2c39217a',
    messagingSenderId: '270100716047',
    projectId: 'applygit',
    storageBucket: 'applygit.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsyodqaYO_wDfhyBxYDbB57rvyNcwBzKA',
    appId: '1:270100716047:ios:f916566234b424ce39217a',
    messagingSenderId: '270100716047',
    projectId: 'applygit',
    storageBucket: 'applygit.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
